/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedPedidosNovoRouteImport } from './routes/_authenticated/pedidos.novo'
import { Route as AuthenticatedPedidosMeusRouteImport } from './routes/_authenticated/pedidos.meus'
import { Route as AuthenticatedLogisticaPainelRouteImport } from './routes/_authenticated/logistica.painel'
import { Route as AuthenticatedDevConfigRouteImport } from './routes/_authenticated/dev.config'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPermissoesGlobaisRouteImport } from './routes/_authenticated/admin.permissoes-globais'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosNovoRoute =
  AuthenticatedPedidosNovoRouteImport.update({
    id: '/pedidos/novo',
    path: '/pedidos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosMeusRoute =
  AuthenticatedPedidosMeusRouteImport.update({
    id: '/pedidos/meus',
    path: '/pedidos/meus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticaPainelRoute =
  AuthenticatedLogisticaPainelRouteImport.update({
    id: '/logistica/painel',
    path: '/logistica/painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevConfigRoute = AuthenticatedDevConfigRouteImport.update({
  id: '/dev/config',
  path: '/dev/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissoesGlobaisRoute =
  AuthenticatedAdminPermissoesGlobaisRouteImport.update({
    id: '/admin/permissoes-globais',
    path: '/admin/permissoes-globais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/permissoes-globais': typeof AuthenticatedAdminPermissoesGlobaisRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dev/config': typeof AuthenticatedDevConfigRoute
  '/logistica/painel': typeof AuthenticatedLogisticaPainelRoute
  '/pedidos/meus': typeof AuthenticatedPedidosMeusRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/permissoes-globais': typeof AuthenticatedAdminPermissoesGlobaisRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/dev/config': typeof AuthenticatedDevConfigRoute
  '/logistica/painel': typeof AuthenticatedLogisticaPainelRoute
  '/pedidos/meus': typeof AuthenticatedPedidosMeusRoute
  '/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/permissoes-globais': typeof AuthenticatedAdminPermissoesGlobaisRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/dev/config': typeof AuthenticatedDevConfigRoute
  '/_authenticated/logistica/painel': typeof AuthenticatedLogisticaPainelRoute
  '/_authenticated/pedidos/meus': typeof AuthenticatedPedidosMeusRoute
  '/_authenticated/pedidos/novo': typeof AuthenticatedPedidosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/admin/permissoes-globais'
    | '/admin/usuarios'
    | '/dev/config'
    | '/logistica/painel'
    | '/pedidos/meus'
    | '/pedidos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/admin/permissoes-globais'
    | '/admin/usuarios'
    | '/dev/config'
    | '/logistica/painel'
    | '/pedidos/meus'
    | '/pedidos/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/permissoes-globais'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/dev/config'
    | '/_authenticated/logistica/painel'
    | '/_authenticated/pedidos/meus'
    | '/_authenticated/pedidos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/novo': {
      id: '/_authenticated/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AuthenticatedPedidosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/meus': {
      id: '/_authenticated/pedidos/meus'
      path: '/pedidos/meus'
      fullPath: '/pedidos/meus'
      preLoaderRoute: typeof AuthenticatedPedidosMeusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistica/painel': {
      id: '/_authenticated/logistica/painel'
      path: '/logistica/painel'
      fullPath: '/logistica/painel'
      preLoaderRoute: typeof AuthenticatedLogisticaPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/config': {
      id: '/_authenticated/dev/config'
      path: '/dev/config'
      fullPath: '/dev/config'
      preLoaderRoute: typeof AuthenticatedDevConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissoes-globais': {
      id: '/_authenticated/admin/permissoes-globais'
      path: '/admin/permissoes-globais'
      fullPath: '/admin/permissoes-globais'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesGlobaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminPermissoesGlobaisRoute: typeof AuthenticatedAdminPermissoesGlobaisRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedDevConfigRoute: typeof AuthenticatedDevConfigRoute
  AuthenticatedLogisticaPainelRoute: typeof AuthenticatedLogisticaPainelRoute
  AuthenticatedPedidosMeusRoute: typeof AuthenticatedPedidosMeusRoute
  AuthenticatedPedidosNovoRoute: typeof AuthenticatedPedidosNovoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminPermissoesGlobaisRoute:
    AuthenticatedAdminPermissoesGlobaisRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedDevConfigRoute: AuthenticatedDevConfigRoute,
  AuthenticatedLogisticaPainelRoute: AuthenticatedLogisticaPainelRoute,
  AuthenticatedPedidosMeusRoute: AuthenticatedPedidosMeusRoute,
  AuthenticatedPedidosNovoRoute: AuthenticatedPedidosNovoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
